//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace PortalWSClient.PortalWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QuerySoap", Namespace="portalquery.just.ro")]
    public partial class Query : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CautareDosareOperationCompleted;
        
        private System.Threading.SendOrPostCallback CautareSedinteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Query() {
            this.Url = global::PortalWSClient.Properties.Settings.Default.PortalWSClient_PortalWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CautareDosareCompletedEventHandler CautareDosareCompleted;
        
        /// <remarks/>
        public event CautareSedinteCompletedEventHandler CautareSedinteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("portalquery.just.ro/HelloWorld", RequestNamespace="portalquery.just.ro", ResponseNamespace="portalquery.just.ro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("portalquery.just.ro/CautareDosare", RequestNamespace="portalquery.just.ro", ResponseNamespace="portalquery.just.ro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Dosar[] CautareDosare(string numarDosar, string obiectDosar, string numeParte, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<Institutie> institutie, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> dataStart, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> dataStop) {
            object[] results = this.Invoke("CautareDosare", new object[] {
                        numarDosar,
                        obiectDosar,
                        numeParte,
                        institutie,
                        dataStart,
                        dataStop});
            return ((Dosar[])(results[0]));
        }
        
        /// <remarks/>
        public void CautareDosareAsync(string numarDosar, string obiectDosar, string numeParte, System.Nullable<Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop) {
            this.CautareDosareAsync(numarDosar, obiectDosar, numeParte, institutie, dataStart, dataStop, null);
        }
        
        /// <remarks/>
        public void CautareDosareAsync(string numarDosar, string obiectDosar, string numeParte, System.Nullable<Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop, object userState) {
            if ((this.CautareDosareOperationCompleted == null)) {
                this.CautareDosareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCautareDosareOperationCompleted);
            }
            this.InvokeAsync("CautareDosare", new object[] {
                        numarDosar,
                        obiectDosar,
                        numeParte,
                        institutie,
                        dataStart,
                        dataStop}, this.CautareDosareOperationCompleted, userState);
        }
        
        private void OnCautareDosareOperationCompleted(object arg) {
            if ((this.CautareDosareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CautareDosareCompleted(this, new CautareDosareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("portalquery.just.ro/CautareSedinte", RequestNamespace="portalquery.just.ro", ResponseNamespace="portalquery.just.ro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sedinta[] CautareSedinte(System.DateTime dataSedinta, Institutie institutie) {
            object[] results = this.Invoke("CautareSedinte", new object[] {
                        dataSedinta,
                        institutie});
            return ((Sedinta[])(results[0]));
        }
        
        /// <remarks/>
        public void CautareSedinteAsync(System.DateTime dataSedinta, Institutie institutie) {
            this.CautareSedinteAsync(dataSedinta, institutie, null);
        }
        
        /// <remarks/>
        public void CautareSedinteAsync(System.DateTime dataSedinta, Institutie institutie, object userState) {
            if ((this.CautareSedinteOperationCompleted == null)) {
                this.CautareSedinteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCautareSedinteOperationCompleted);
            }
            this.InvokeAsync("CautareSedinte", new object[] {
                        dataSedinta,
                        institutie}, this.CautareSedinteOperationCompleted, userState);
        }
        
        private void OnCautareSedinteOperationCompleted(object arg) {
            if ((this.CautareSedinteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CautareSedinteCompleted(this, new CautareSedinteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public enum Institutie {
        
        /// <remarks/>
        CurteadeApelBUCURESTI,
        
        /// <remarks/>
        TribunalulBUCURESTI,
        
        /// <remarks/>
        JudecatoriaSECTORUL4BUCURESTI,
        
        /// <remarks/>
        TribunalulTIMIS,
        
        /// <remarks/>
        CurteadeApelBACAU,
        
        /// <remarks/>
        CurteadeApelCLUJ,
        
        /// <remarks/>
        CurteadeApelORADEA,
        
        /// <remarks/>
        CurteadeApelCONSTANTA,
        
        /// <remarks/>
        CurteadeApelSUCEAVA,
        
        /// <remarks/>
        TribunalulBOTOSANI,
        
        /// <remarks/>
        CurteadeApelPLOIESTI,
        
        /// <remarks/>
        CurteadeApelTARGUMURES,
        
        /// <remarks/>
        CurteadeApelGALATI,
        
        /// <remarks/>
        CurteadeApelIASI,
        
        /// <remarks/>
        CurteadeApelPITESTI,
        
        /// <remarks/>
        CurteadeApelCRAIOVA,
        
        /// <remarks/>
        JudecatoriaARAD,
        
        /// <remarks/>
        CurteadeApelALBAIULIA,
        
        /// <remarks/>
        CurteadeApelTIMISOARA,
        
        /// <remarks/>
        TribunalulBRASOV,
        
        /// <remarks/>
        TribunalulDOLJ,
        
        /// <remarks/>
        CurteadeApelBRASOV,
        
        /// <remarks/>
        CurteaMilitaradeApelBUCURESTI,
        
        /// <remarks/>
        TribunalulSATUMARE,
        
        /// <remarks/>
        TribunalulSALAJ,
        
        /// <remarks/>
        TribunalulSIBIU,
        
        /// <remarks/>
        TribunalulSUCEAVA,
        
        /// <remarks/>
        TribunalulTELEORMAN,
        
        /// <remarks/>
        TribunalulTULCEA,
        
        /// <remarks/>
        TribunalulVASLUI,
        
        /// <remarks/>
        TribunalulVALCEA,
        
        /// <remarks/>
        TribunalulVRANCEA,
        
        /// <remarks/>
        TribunalulMilitarBUCURESTI,
        
        /// <remarks/>
        TribunalulILFOV,
        
        /// <remarks/>
        JudecatoriaBUFTEA,
        
        /// <remarks/>
        TribunalulGORJ,
        
        /// <remarks/>
        TribunalulHARGHITA,
        
        /// <remarks/>
        TribunalulHUNEDOARA,
        
        /// <remarks/>
        TribunalulIALOMITA,
        
        /// <remarks/>
        TribunalulIASI,
        
        /// <remarks/>
        TribunalulMARAMURES,
        
        /// <remarks/>
        TribunalulMEHEDINTI,
        
        /// <remarks/>
        TribunalulMURES,
        
        /// <remarks/>
        TribunalulNEAMT,
        
        /// <remarks/>
        TribunalulOLT,
        
        /// <remarks/>
        TribunalulPRAHOVA,
        
        /// <remarks/>
        TribunalulALBA,
        
        /// <remarks/>
        TribunalulARAD,
        
        /// <remarks/>
        TribunalulARGES,
        
        /// <remarks/>
        TribunalulBACAU,
        
        /// <remarks/>
        TribunalulBIHOR,
        
        /// <remarks/>
        TribunalulBISTRITANASAUD,
        
        /// <remarks/>
        TribunalulBRAILA,
        
        /// <remarks/>
        TribunalulBUZAU,
        
        /// <remarks/>
        TribunalulCARASSEVERIN,
        
        /// <remarks/>
        TribunalulCALARASI,
        
        /// <remarks/>
        TribunalulCLUJ,
        
        /// <remarks/>
        TribunalulCONSTANTA,
        
        /// <remarks/>
        TribunalulCOVASNA,
        
        /// <remarks/>
        TribunalulDAMBOVITA,
        
        /// <remarks/>
        TribunalulGALATI,
        
        /// <remarks/>
        TribunalulGIURGIU,
        
        /// <remarks/>
        JudecatoriaADJUD,
        
        /// <remarks/>
        JudecatoriaAGNITA,
        
        /// <remarks/>
        JudecatoriaAIUD,
        
        /// <remarks/>
        JudecatoriaALBAIULIA,
        
        /// <remarks/>
        JudecatoriaALESD,
        
        /// <remarks/>
        JudecatoriaBABADAG,
        
        /// <remarks/>
        JudecatoriaBACAU,
        
        /// <remarks/>
        JudecatoriaBAIADEARAMA,
        
        /// <remarks/>
        JudecatoriaBAIAMARE,
        
        /// <remarks/>
        JudecatoriaBAILESTI,
        
        /// <remarks/>
        JudecatoriaBALS,
        
        /// <remarks/>
        JudecatoriaBALCESTI,
        
        /// <remarks/>
        JudecatoriaBECLEAN,
        
        /// <remarks/>
        JudecatoriaBEIUS,
        
        /// <remarks/>
        JudecatoriaBICAZ,
        
        /// <remarks/>
        JudecatoriaBARLAD,
        
        /// <remarks/>
        JudecatoriaBISTRITA,
        
        /// <remarks/>
        JudecatoriaBLAJ,
        
        /// <remarks/>
        JudecatoriaBOLINTINVALE,
        
        /// <remarks/>
        JudecatoriaBOTOSANI,
        
        /// <remarks/>
        JudecatoriaBOZOVICI,
        
        /// <remarks/>
        JudecatoriaBRAD,
        
        /// <remarks/>
        JudecatoriaBRAILA,
        
        /// <remarks/>
        JudecatoriaBRASOV,
        
        /// <remarks/>
        JudecatoriaBREZOI,
        
        /// <remarks/>
        JudecatoriaBUHUSI,
        
        /// <remarks/>
        JudecatoriaBUZAU,
        
        /// <remarks/>
        JudecatoriaCALAFAT,
        
        /// <remarks/>
        JudecatoriaCALARASI,
        
        /// <remarks/>
        JudecatoriaCAMPENI,
        
        /// <remarks/>
        JudecatoriaCAMPINA,
        
        /// <remarks/>
        JudecatoriaCAMPULUNG,
        
        /// <remarks/>
        JudecatoriaCAMPULUNGMOLDOVENESC,
        
        /// <remarks/>
        JudecatoriaCARACAL,
        
        /// <remarks/>
        JudecatoriaCARANSEBES,
        
        /// <remarks/>
        JudecatoriaCHISINEUCRIS,
        
        /// <remarks/>
        JudecatoriaCLUJNAPOCA,
        
        /// <remarks/>
        JudecatoriaCONSTANTA,
        
        /// <remarks/>
        JudecatoriaCORABIA,
        
        /// <remarks/>
        JudecatoriaCOSTESTI,
        
        /// <remarks/>
        JudecatoriaCRAIOVA,
        
        /// <remarks/>
        JudecatoriaCURTEADEARGES,
        
        /// <remarks/>
        JudecatoriaDarabani,
        
        /// <remarks/>
        JudecatoriaCAREI,
        
        /// <remarks/>
        JudecatoriaDEJ,
        
        /// <remarks/>
        JudecatoriaDETA,
        
        /// <remarks/>
        JudecatoriaDEVA,
        
        /// <remarks/>
        JudecatoriaDOROHOI,
        
        /// <remarks/>
        JudecatoriaDRAGASANI,
        
        /// <remarks/>
        JudecatoriaDRAGOMIRESTI,
        
        /// <remarks/>
        JudecatoriaDROBETATURNUSEVERIN,
        
        /// <remarks/>
        JudecatoriaFAGARAS,
        
        /// <remarks/>
        JudecatoriaFALTICENI,
        
        /// <remarks/>
        JudecatoriaFAUREI,
        
        /// <remarks/>
        JudecatoriaFETESTI,
        
        /// <remarks/>
        JudecatoriaFILIASI,
        
        /// <remarks/>
        JudecatoriaFOCSANI,
        
        /// <remarks/>
        JudecatoriaGAESTI,
        
        /// <remarks/>
        JudecatoriaGALATI,
        
        /// <remarks/>
        JudecatoriaGHEORGHENI,
        
        /// <remarks/>
        JudecatoriaGHERLA,
        
        /// <remarks/>
        JudecatoriaGIURGIU,
        
        /// <remarks/>
        JudecatoriaGURAHUMORULUI,
        
        /// <remarks/>
        JudecatoriaGURAHONT,
        
        /// <remarks/>
        JudecatoriaHARLAU,
        
        /// <remarks/>
        JudecatoriaHATEG,
        
        /// <remarks/>
        JudecatoriaHOREZU,
        
        /// <remarks/>
        JudecatoriaHUEDIN,
        
        /// <remarks/>
        JudecatoriaHUNEDOARA,
        
        /// <remarks/>
        JudecatoriaHUSI,
        
        /// <remarks/>
        JudecatoriaIASI,
        
        /// <remarks/>
        JudecatoriaINEU,
        
        /// <remarks/>
        JudecatoriaINSURATEI,
        
        /// <remarks/>
        JudecatoriaINTORSURABUZAULUI,
        
        /// <remarks/>
        JudecatoriaLEHLIUGARA,
        
        /// <remarks/>
        JudecatoriaLIPOVA,
        
        /// <remarks/>
        JudecatoriaLUDUS,
        
        /// <remarks/>
        JudecatoriaLUGOJ,
        
        /// <remarks/>
        JudecatoriaMACIN,
        
        /// <remarks/>
        JudecatoriaMANGALIA,
        
        /// <remarks/>
        JudecatoriaMARGHITA,
        
        /// <remarks/>
        JudecatoriaMEDGIDIA,
        
        /// <remarks/>
        JudecatoriaMEDIAS,
        
        /// <remarks/>
        JudecatoriaMIERCUREACIUC,
        
        /// <remarks/>
        JudecatoriaMIZIL,
        
        /// <remarks/>
        JudecatoriaMOINESTI,
        
        /// <remarks/>
        JudecatoriaMOLDOVANOUA,
        
        /// <remarks/>
        JudecatoriaMORENI,
        
        /// <remarks/>
        JudecatoriaMOTRU,
        
        /// <remarks/>
        JudecatoriaMURGENI,
        
        /// <remarks/>
        JudecatoriaNASAUD,
        
        /// <remarks/>
        JudecatoriaNEGRESTIOAS,
        
        /// <remarks/>
        JudecatoriaNOVACI,
        
        /// <remarks/>
        JudecatoriaODORHEIULSECUIESC,
        
        /// <remarks/>
        JudecatoriaOLTENITA,
        
        /// <remarks/>
        JudecatoriaONESTI,
        
        /// <remarks/>
        JudecatoriaORADEA,
        
        /// <remarks/>
        JudecatoriaORASTIE,
        
        /// <remarks/>
        JudecatoriaORAVITA,
        
        /// <remarks/>
        JudecatoriaORSOVA,
        
        /// <remarks/>
        JudecatoriaPANCIU,
        
        /// <remarks/>
        JudecatoriaPATARLAGELE,
        
        /// <remarks/>
        JudecatoriaPETROSANI,
        
        /// <remarks/>
        JudecatoriaPIATRANEAMT,
        
        /// <remarks/>
        JudecatoriaPITESTI,
        
        /// <remarks/>
        JudecatoriaPLOIESTI,
        
        /// <remarks/>
        JudecatoriaPOGOANELE,
        
        /// <remarks/>
        JudecatoriaPUCIOASA,
        
        /// <remarks/>
        JudecatoriaRACARI,
        
        /// <remarks/>
        JudecatoriaRADAUTI,
        
        /// <remarks/>
        JudecatoriaRADUCANENI,
        
        /// <remarks/>
        JudecatoriaRAMNICUSARAT,
        
        /// <remarks/>
        JudecatoriaRAMNICUVALCEA,
        
        /// <remarks/>
        JudecatoriaREGHIN,
        
        /// <remarks/>
        JudecatoriaRESITA,
        
        /// <remarks/>
        JudecatoriaROMAN,
        
        /// <remarks/>
        JudecatoriaROSIORIDEVEDE,
        
        /// <remarks/>
        JudecatoriaRUPEA,
        
        /// <remarks/>
        JudecatoriaSALISTE,
        
        /// <remarks/>
        JudecatoriaSANNICOLAULMARE,
        
        /// <remarks/>
        JudecatoriaSATUMARE,
        
        /// <remarks/>
        JudecatoriaSAVENI,
        
        /// <remarks/>
        JudecatoriaSEBES,
        
        /// <remarks/>
        JudecatoriaSECTORUL1BUCURESTI,
        
        /// <remarks/>
        JudecatoriaSECTORUL2BUCURESTI,
        
        /// <remarks/>
        JudecatoriaSECTORUL3BUCURESTI,
        
        /// <remarks/>
        JudecatoriaSECTORUL5BUCURESTI,
        
        /// <remarks/>
        JudecatoriaSECTORUL6BUCURESTI,
        
        /// <remarks/>
        JudecatoriaSEGARCEA,
        
        /// <remarks/>
        JudecatoriaSFANTUGHEORGHE,
        
        /// <remarks/>
        JudecatoriaSIBIU,
        
        /// <remarks/>
        JudecatoriaSIGHETUMARMATIEI,
        
        /// <remarks/>
        JudecatoriaSIGHISOARA,
        
        /// <remarks/>
        JudecatoriaSIMLEULSILVANIEI,
        
        /// <remarks/>
        JudecatoriaSINAIA,
        
        /// <remarks/>
        JudecatoriaSLATINA,
        
        /// <remarks/>
        JudecatoriaSLOBOZIA,
        
        /// <remarks/>
        JudecatoriaSTREHAIA,
        
        /// <remarks/>
        JudecatoriaSUCEAVA,
        
        /// <remarks/>
        JudecatoriaTARGOVISTE,
        
        /// <remarks/>
        JudecatoriaTARGUBUJOR,
        
        /// <remarks/>
        JudecatoriaTARGUCARBUNESTI,
        
        /// <remarks/>
        JudecatoriaTARGUJIU,
        
        /// <remarks/>
        JudecatoriaTARGULAPUS,
        
        /// <remarks/>
        JudecatoriaTARGUMURES,
        
        /// <remarks/>
        JudecatoriaTARGUNEAMT,
        
        /// <remarks/>
        JudecatoriaTARGUSECUIESC,
        
        /// <remarks/>
        JudecatoriaTARNAVENI,
        
        /// <remarks/>
        JudecatoriaTECUCI,
        
        /// <remarks/>
        JudecatoriaTIMISOARA,
        
        /// <remarks/>
        JudecatoriaTOPLITA,
        
        /// <remarks/>
        JudecatoriaTULCEA,
        
        /// <remarks/>
        JudecatoriaTURDA,
        
        /// <remarks/>
        JudecatoriaTURNUMAGURELE,
        
        /// <remarks/>
        JudecatoriaURZICENI,
        
        /// <remarks/>
        JudecatoriaVALENIIDEMUNTE,
        
        /// <remarks/>
        JudecatoriaVANJUMARE,
        
        /// <remarks/>
        JudecatoriaVASLUI,
        
        /// <remarks/>
        JudecatoriaVATRADORNEI,
        
        /// <remarks/>
        JudecatoriaVIDELE,
        
        /// <remarks/>
        JudecatoriaVISEUDESUS,
        
        /// <remarks/>
        JudecatoriaZALAU,
        
        /// <remarks/>
        JudecatoriaZARNESTI,
        
        /// <remarks/>
        JudecatoriaZIMNICEA,
        
        /// <remarks/>
        TribunalulMilitarIASI,
        
        /// <remarks/>
        JudecatoriaALEXANDRIA,
        
        /// <remarks/>
        TribunalulMilitarTIMISOARA,
        
        /// <remarks/>
        TribunalulMilitarCLUJNAPOCA,
        
        /// <remarks/>
        TribunalulMilitarTeritorialBUCURESTI,
        
        /// <remarks/>
        JudecatoriaAVRIG,
        
        /// <remarks/>
        JudecatoriaTOPOLOVENI,
        
        /// <remarks/>
        JudecatoriaPODUTURCULUI,
        
        /// <remarks/>
        JudecatoriaFAGET,
        
        /// <remarks/>
        JudecatoriaSALONTA,
        
        /// <remarks/>
        JudecatoriaLIESTI,
        
        /// <remarks/>
        JudecatoriaHARSOVA,
        
        /// <remarks/>
        JudecatoriaSOMCUTAMARE,
        
        /// <remarks/>
        JudecatoriaPASCANI,
        
        /// <remarks/>
        TribunalulComercialARGES,
        
        /// <remarks/>
        TribunalulComercialCLUJ,
        
        /// <remarks/>
        TribunalulComercialMURES,
        
        /// <remarks/>
        TribunalulpentruminoriSifamilieBRASOV,
        
        /// <remarks/>
        JudecatoriaCORNETU,
        
        /// <remarks/>
        JudecatoriaJIBOU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class Dosar {
        
        private DosarParte[] partiField;
        
        private DosarSedinta[] sedinteField;
        
        private DosarCaleAtac[] caiAtacField;
        
        private string numarField;
        
        private string numarVechiField;
        
        private System.DateTime dataField;
        
        private Institutie institutieField;
        
        private string departamentField;
        
        private CategorieCaz categorieCazField;
        
        private StadiuProcesual stadiuProcesualField;
        
        private string obiectField;
        
        /// <remarks/>
        public DosarParte[] parti {
            get {
                return this.partiField;
            }
            set {
                this.partiField = value;
            }
        }
        
        /// <remarks/>
        public DosarSedinta[] sedinte {
            get {
                return this.sedinteField;
            }
            set {
                this.sedinteField = value;
            }
        }
        
        /// <remarks/>
        public DosarCaleAtac[] caiAtac {
            get {
                return this.caiAtacField;
            }
            set {
                this.caiAtacField = value;
            }
        }
        
        /// <remarks/>
        public string numar {
            get {
                return this.numarField;
            }
            set {
                this.numarField = value;
            }
        }
        
        /// <remarks/>
        public string numarVechi {
            get {
                return this.numarVechiField;
            }
            set {
                this.numarVechiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Institutie institutie {
            get {
                return this.institutieField;
            }
            set {
                this.institutieField = value;
            }
        }
        
        /// <remarks/>
        public string departament {
            get {
                return this.departamentField;
            }
            set {
                this.departamentField = value;
            }
        }
        
        /// <remarks/>
        public CategorieCaz categorieCaz {
            get {
                return this.categorieCazField;
            }
            set {
                this.categorieCazField = value;
            }
        }
        
        /// <remarks/>
        public StadiuProcesual stadiuProcesual {
            get {
                return this.stadiuProcesualField;
            }
            set {
                this.stadiuProcesualField = value;
            }
        }
        
        /// <remarks/>
        public string obiect {
            get {
                return this.obiectField;
            }
            set {
                this.obiectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class DosarParte {
        
        private string numeField;
        
        private string calitateParteField;
        
        /// <remarks/>
        public string nume {
            get {
                return this.numeField;
            }
            set {
                this.numeField = value;
            }
        }
        
        /// <remarks/>
        public string calitateParte {
            get {
                return this.calitateParteField;
            }
            set {
                this.calitateParteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class SedintaDosar {
        
        private string numarField;
        
        private string numar_vechiField;
        
        private System.DateTime dataField;
        
        private string oraField;
        
        private CategorieCaz categorieCazField;
        
        private StadiuProcesual stadiuProcesualField;
        
        /// <remarks/>
        public string numar {
            get {
                return this.numarField;
            }
            set {
                this.numarField = value;
            }
        }
        
        /// <remarks/>
        public string numar_vechi {
            get {
                return this.numar_vechiField;
            }
            set {
                this.numar_vechiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string ora {
            get {
                return this.oraField;
            }
            set {
                this.oraField = value;
            }
        }
        
        /// <remarks/>
        public CategorieCaz categorieCaz {
            get {
                return this.categorieCazField;
            }
            set {
                this.categorieCazField = value;
            }
        }
        
        /// <remarks/>
        public StadiuProcesual stadiuProcesual {
            get {
                return this.stadiuProcesualField;
            }
            set {
                this.stadiuProcesualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public enum CategorieCaz {
        
        /// <remarks/>
        Penal,
        
        /// <remarks/>
        Civil,
        
        /// <remarks/>
        Comercial,
        
        /// <remarks/>
        Contenciosadministrativsifiscal,
        
        /// <remarks/>
        Minorisifamilie,
        
        /// <remarks/>
        Litigiidemunca,
        
        /// <remarks/>
        Altematerii,
        
        /// <remarks/>
        Asigurarisociale,
        
        /// <remarks/>
        Faliment,
        
        /// <remarks/>
        ProprietateIntelectuala,
        
        /// <remarks/>
        Dreptmaritimsifluvial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public enum StadiuProcesual {
        
        /// <remarks/>
        Fond,
        
        /// <remarks/>
        Apel,
        
        /// <remarks/>
        Recurs,
        
        /// <remarks/>
        Recursinanulare,
        
        /// <remarks/>
        Recursininteresullegii,
        
        /// <remarks/>
        Contestatie,
        
        /// <remarks/>
        Revizuire,
        
        /// <remarks/>
        Contestatieinanulare,
        
        /// <remarks/>
        Stabilireacompetentei,
        
        /// <remarks/>
        Recursimpotrivaincheierii,
        
        /// <remarks/>
        Recuzare,
        
        /// <remarks/>
        Stramutare,
        
        /// <remarks/>
        Indreptareeroaremateriala,
        
        /// <remarks/>
        ContestatieinanulareFond,
        
        /// <remarks/>
        ContestatieinanulareApel,
        
        /// <remarks/>
        ContestatieinanulareRecurs,
        
        /// <remarks/>
        RevizuireFond,
        
        /// <remarks/>
        RevizuireApel,
        
        /// <remarks/>
        RevizuireRecurs,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class Sedinta {
        
        private string departamentField;
        
        private string completField;
        
        private System.DateTime dataField;
        
        private string oraField;
        
        private SedintaDosar[] dosareField;
        
        /// <remarks/>
        public string departament {
            get {
                return this.departamentField;
            }
            set {
                this.departamentField = value;
            }
        }
        
        /// <remarks/>
        public string complet {
            get {
                return this.completField;
            }
            set {
                this.completField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string ora {
            get {
                return this.oraField;
            }
            set {
                this.oraField = value;
            }
        }
        
        /// <remarks/>
        public SedintaDosar[] dosare {
            get {
                return this.dosareField;
            }
            set {
                this.dosareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class DosarCaleAtac {
        
        private System.Nullable<System.DateTime> dataDeclarareField;
        
        private string parteDeclaratoareField;
        
        private string tipCaleAtacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataDeclarare {
            get {
                return this.dataDeclarareField;
            }
            set {
                this.dataDeclarareField = value;
            }
        }
        
        /// <remarks/>
        public string parteDeclaratoare {
            get {
                return this.parteDeclaratoareField;
            }
            set {
                this.parteDeclaratoareField = value;
            }
        }
        
        /// <remarks/>
        public string tipCaleAtac {
            get {
                return this.tipCaleAtacField;
            }
            set {
                this.tipCaleAtacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public partial class DosarSedinta {
        
        private string completField;
        
        private System.DateTime dataField;
        
        private string oraField;
        
        private string solutieField;
        
        private string solutieSumarField;
        
        private System.Nullable<System.DateTime> dataPronuntareField;
        
        private System.Nullable<DocumentSedinta> documentSedintaField;
        
        private string numarDocumentField;
        
        private System.Nullable<System.DateTime> dataDocumentField;
        
        /// <remarks/>
        public string complet {
            get {
                return this.completField;
            }
            set {
                this.completField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string ora {
            get {
                return this.oraField;
            }
            set {
                this.oraField = value;
            }
        }
        
        /// <remarks/>
        public string solutie {
            get {
                return this.solutieField;
            }
            set {
                this.solutieField = value;
            }
        }
        
        /// <remarks/>
        public string solutieSumar {
            get {
                return this.solutieSumarField;
            }
            set {
                this.solutieSumarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataPronuntare {
            get {
                return this.dataPronuntareField;
            }
            set {
                this.dataPronuntareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<DocumentSedinta> documentSedinta {
            get {
                return this.documentSedintaField;
            }
            set {
                this.documentSedintaField = value;
            }
        }
        
        /// <remarks/>
        public string numarDocument {
            get {
                return this.numarDocumentField;
            }
            set {
                this.numarDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataDocument {
            get {
                return this.dataDocumentField;
            }
            set {
                this.dataDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="portalquery.just.ro")]
    public enum DocumentSedinta {
        
        /// <remarks/>
        Cerereinconstatarededrepturi,
        
        /// <remarks/>
        Cerereinrealizarededrepturi,
        
        /// <remarks/>
        Cereredeapel,
        
        /// <remarks/>
        Cererederecurs,
        
        /// <remarks/>
        Cererederecursinanulare,
        
        /// <remarks/>
        Cererederevizuire,
        
        /// <remarks/>
        Contestatieinanulare,
        
        /// <remarks/>
        Cererereconventionala,
        
        /// <remarks/>
        Cereredeinterventieininterespropriu,
        
        /// <remarks/>
        Cereredearatareatitularuluidreptului,
        
        /// <remarks/>
        Cereredechemareingarantie,
        
        /// <remarks/>
        Cereredestramutare,
        
        /// <remarks/>
        Plangereprealabila,
        
        /// <remarks/>
        Cereredereabilitare,
        
        /// <remarks/>
        Cereredeamanareaexecutariipedepsei,
        
        /// <remarks/>
        Cereredeintrerupereaexecutariipedepsei,
        
        /// <remarks/>
        Cereredeliberareconditionata,
        
        /// <remarks/>
        Contestatielaexecutare,
        
        /// <remarks/>
        Cerereprincaresesolicitaincetareaexecutariipedepseiloculdemunca,
        
        /// <remarks/>
        Cererederecursininteresullegii,
        
        /// <remarks/>
        Cererederecunoastereahotararilorpronuntateinstrainatate,
        
        /// <remarks/>
        Cereredeincuviintareaexecutariisiliteahotararilorpronuntateinstrainatate,
        
        /// <remarks/>
        Actiuneintrodusadeadministratorsaulichidatorpentruanulareaunortransferuricucaracterpatrimonial,
        
        /// <remarks/>
        Cereredeaseridicadebitoruluidreptuldeasiconduceactivitatea,
        
        /// <remarks/>
        Cereredeabtinere,
        
        /// <remarks/>
        Cereredeinterventieininteresulalteipersoane,
        
        /// <remarks/>
        Cereredelegalizaredecopii,
        
        /// <remarks/>
        Cereredeconstatareaperimarii,
        
        /// <remarks/>
        Cererederepunereperol,
        
        /// <remarks/>
        Cererederestituireacautiunii,
        
        /// <remarks/>
        Cereredesuspendareaexecutarii,
        
        /// <remarks/>
        Cereredesuspendareaexecutariihotarariiintemeiulart300alin2si3Codproceduracivila,
        
        /// <remarks/>
        Cereredesuspendareaexecutariihotarariipecaleaordonanteipresedintiale,
        
        /// <remarks/>
        Contestatiadebitoruluicontracererilorintroductivealecreditorilorpentruincepereaprocedurii,
        
        /// <remarks/>
        Contestatiadebitoruluisaucreditoruluiimpotrivamasurilorluatedeadministratorlichidator,
        
        /// <remarks/>
        Contestatieimpotrivajudecatoruluisindicdeasecontinuaactivitateaincazdereorganizare,
        
        /// <remarks/>
        Cereredeacordareajutorpublicjudiciar,
        
        /// <remarks/>
        Altecereri,
        
        /// <remarks/>
        Copiehotarare,
        
        /// <remarks/>
        Mandatdeperchezitie,
        
        /// <remarks/>
        Mandatdearestarepreventiva,
        
        /// <remarks/>
        Mandatdearestarepreventivaemisintimpuljudecatii,
        
        /// <remarks/>
        Mandatuldeexecutareapedepseiinchisoriicontinut,
        
        /// <remarks/>
        incheierePerchezitie,
        
        /// <remarks/>
        incheierefinaladezinvestire,
        
        /// <remarks/>
        incheiereindreptareeroaremateriala,
        
        /// <remarks/>
        incheiereabtinere,
        
        /// <remarks/>
        incheiererecuzare,
        
        /// <remarks/>
        incheiereincuviintareascultare,
        
        /// <remarks/>
        Hotararecompletaredispozitiv,
        
        /// <remarks/>
        Cereresolicitaredeciziepenala,
        
        /// <remarks/>
        ConfirmaredeprimireAR,
        
        /// <remarks/>
        Confirmareprimireextrasdecizie,
        
        /// <remarks/>
        Cerereconexaredosare,
        
        /// <remarks/>
        Completaremotiverecursrevizuiresa,
        
        /// <remarks/>
        Adresadesolicitareaultimeiincheieridementinereaarestarii,
        
        /// <remarks/>
        Exceptiedeneconstitutionalitate,
        
        /// <remarks/>
        Adresasolicitarerelatiidelaaltainstanta,
        
        /// <remarks/>
        instiintaredeplataauneiamenzijudiciare,
        
        /// <remarks/>
        Notatelefonica,
        
        /// <remarks/>
        Cereredeacordareasistentajudiciara,
        
        /// <remarks/>
        AdresaBaroupentruacordareasistentajudiciara,
        
        /// <remarks/>
        Confirmaredeprimire,
        
        /// <remarks/>
        Acte,
        
        /// <remarks/>
        Adresadeexecutareaamenziijudiciare,
        
        /// <remarks/>
        incheieremasuripreventivefazadejudecata,
        
        /// <remarks/>
        Raportamanuntit,
        
        /// <remarks/>
        Raportasuprafondurilorobtinutedinvanzare,
        
        /// <remarks/>
        Tabelpreliminar,
        
        /// <remarks/>
        Raportfinal,
        
        /// <remarks/>
        Raportdeactivitate,
        
        /// <remarks/>
        Tabeldefinitiv,
        
        /// <remarks/>
        Tabelsuplimentar,
        
        /// <remarks/>
        Tabeldefinitivconsolidat,
        
        /// <remarks/>
        ContestatielaTabel,
        
        /// <remarks/>
        Actiuneinanulareactefrauduloase,
        
        /// <remarks/>
        Obiectiunilaraportuladministratoruluilichidatoruluijudiciar,
        
        /// <remarks/>
        Cerereinchidereprocedura,
        
        /// <remarks/>
        Contestatietergiversarecauza,
        
        /// <remarks/>
        Plangerecontestatietergiversare,
        
        /// <remarks/>
        Plangere,
        
        /// <remarks/>
        Denunt,
        
        /// <remarks/>
        Sesizare,
        
        /// <remarks/>
        Plangereimpotrivamasuriiarestariipreventivedispusedeprocuror,
        
        /// <remarks/>
        Cereredeliberareprovizoriesubcontroljudiciar,
        
        /// <remarks/>
        Cereredeliberareprovizoriepecautiune,
        
        /// <remarks/>
        Plangereimpotrivamasurilorsiactelordeurmarirepenala,
        
        /// <remarks/>
        Rezolutiededisjungere,
        
        /// <remarks/>
        Hotararededisjungere,
        
        /// <remarks/>
        Cereredecontopireapedepselor,
        
        /// <remarks/>
        Cereredemodificareapedepseiconformart449Coddeprocedurapenala,
        
        /// <remarks/>
        Cereredeinlaturaresaumodificareapedepseiconformart458Coddeprocedurapenala,
        
        /// <remarks/>
        Plangereimpotrivaactelorsimasurilorprocurorului,
        
        /// <remarks/>
        Cereredeconfirmareamasuriiinternariimedicaleprovizorii,
        
        /// <remarks/>
        Cereredeinlocuireamasuriiinternariimedicale,
        
        /// <remarks/>
        Cereredeincetareamasuriiinternariiprovizorii,
        
        /// <remarks/>
        Cererederevocareamasuriidesiguranta,
        
        /// <remarks/>
        Cererederevocareasuspendariiexecutariipedepsei,
        
        /// <remarks/>
        Cereredeanulareasuspendariiexecutariipedepsei,
        
        /// <remarks/>
        Cererederevocareaexecutariipedepseilaloculdemunca,
        
        /// <remarks/>
        Cereredeanulareaexecutariipedepseilaloculdemunca,
        
        /// <remarks/>
        Declaratiedeapel,
        
        /// <remarks/>
        Declaratiederecurs,
        
        /// <remarks/>
        Cererederecuzare,
        
        /// <remarks/>
        Cereredeschimbarealoculuiexecutariipedepsei,
        
        /// <remarks/>
        Cereredeprelungireaarestariipreventive,
        
        /// <remarks/>
        Cereredeextradare,
        
        /// <remarks/>
        Cereredecomisierogatorie,
        
        /// <remarks/>
        Cereredetransferdeproceduripenale,
        
        /// <remarks/>
        Cereredeinmanaredeacte,
        
        /// <remarks/>
        Plangereimpotrivamasurilorasiguratorii,
        
        /// <remarks/>
        Cererederecunoastereahotararilorsiaaltoractejudiciarepronuntateinstrainatate,
        
        /// <remarks/>
        Cereredeinlocuireapedepsei,
        
        /// <remarks/>
        Cereredereconstituireadosarelorsauaaltorinscrisuri,
        
        /// <remarks/>
        Sesizareaorganuluicompetent,
        
        /// <remarks/>
        Cereredeindreptareauneierorimateriale,
        
        /// <remarks/>
        Certificat,
        
        /// <remarks/>
        Declaratiedepartevatamata,
        
        /// <remarks/>
        Mandatdearestareemisinlipsa,
        
        /// <remarks/>
        Procesverbaldeefectuareaactelorpremergatoare,
        
        /// <remarks/>
        Procesverbaldesesizaredinoficiu,
        
        /// <remarks/>
        Procesverbaldeconstatareafaptei,
        
        /// <remarks/>
        Procesverbaldeincepereaurmaririipenale,
        
        /// <remarks/>
        Procesverbaldecercetarelafatalocului,
        
        /// <remarks/>
        Procesverbaldeperchezitiesiridicaredeobiecte,
        
        /// <remarks/>
        Procesverbaldereconstituireafaptei,
        
        /// <remarks/>
        Procesverbaldeprezentareamaterialuluideurmarirepenala,
        
        /// <remarks/>
        Procesverbaldeinregistrariaudiosivideo,
        
        /// <remarks/>
        Procesverbaldeconfruntare,
        
        /// <remarks/>
        Procesverbalconformart91indice234,
        
        /// <remarks/>
        Procesverbaldesechestrusiinscriptieipotecara,
        
        /// <remarks/>
        Procesverbaldeindreptareaerorilormateriale,
        
        /// <remarks/>
        Autorizatiedeinregistrarepebandamagneticaaunorconvorbiri,
        
        /// <remarks/>
        Autorizatiedeinregistrarepebandamagneticaaunorimagini,
        
        /// <remarks/>
        Autorizatieemisadeprocurorconformart111Cpp,
        
        /// <remarks/>
        Raportdeexpertiza,
        
        /// <remarks/>
        Raportdeexpertizacontabila,
        
        /// <remarks/>
        Raportdeexpertizatehnica,
        
        /// <remarks/>
        Raportdeexpertizapsihiatrica,
        
        /// <remarks/>
        Raportdeexpertizamedicolegala,
        
        /// <remarks/>
        Raportdeconstataretehnicostiintifica,
        
        /// <remarks/>
        Raportdeconstataremedicolegala,
        
        /// <remarks/>
        Ordonantacuprivirelamasurilepreventiveretinere,
        
        /// <remarks/>
        AvizalMinistruluiJustitieipentrumagistrati,
        
        /// <remarks/>
        executorijudecatorestisinotaridecercetare,
        
        /// <remarks/>
        AvizalParlamentului,
        
        /// <remarks/>
        Ordonantacuprivirelamasurilepreventivearestare,
        
        /// <remarks/>
        Ordonantacuprivirelamasurilepreventiveobligareadeanuparasilocalitatea,
        
        /// <remarks/>
        Memoriuderecursinanulare,
        
        /// <remarks/>
        Scrisoare,
        
        /// <remarks/>
        Memoriu,
        
        /// <remarks/>
        Opinie,
        
        /// <remarks/>
        Notadeaudienta,
        
        /// <remarks/>
        Cereritransferpersoanecondamnate,
        
        /// <remarks/>
        Informare,
        
        /// <remarks/>
        Rechizitoriu,
        
        /// <remarks/>
        SesizareacomisieidedisciplinaaMinisteruluiPublic,
        
        /// <remarks/>
        HotarareacomisieidedisciplinaaMinisteruluiPublic,
        
        /// <remarks/>
        Notaobservatorie,
        
        /// <remarks/>
        Cereredechemareinjudecata,
        
        /// <remarks/>
        Declaratiedeinculpat,
        
        /// <remarks/>
        Declaratiedeinvinuit,
        
        /// <remarks/>
        Declaratiedemartor,
        
        /// <remarks/>
        Declaratiedepartecivila,
        
        /// <remarks/>
        Declaratiedeparteresponsabilacivilmente,
        
        /// <remarks/>
        Mandatdearestare,
        
        /// <remarks/>
        Mandatdeaducere,
        
        /// <remarks/>
        Autorizatiedeperchezitie,
        
        /// <remarks/>
        Ordonantaaprocurorului,
        
        /// <remarks/>
        Procesverbaldeindeplinireaproceduriidecitare,
        
        /// <remarks/>
        Cazier,
        
        /// <remarks/>
        Cereredecontestareinanulare,
        
        /// <remarks/>
        incheiereSuspendare,
        
        /// <remarks/>
        incheieremasuripreventivefazadeUP,
        
        /// <remarks/>
        incheiereAmanareinitialaapronuntarii,
        
        /// <remarks/>
        incheiereAmanareulterioaraapronuntarii,
        
        /// <remarks/>
        incheieredesedinta,
        
        /// <remarks/>
        incheierePerimare,
        
        /// <remarks/>
        Hotarare,
        
        /// <remarks/>
        incheieredesedintasecreta,
        
        /// <remarks/>
        Acteindovedireacererii,
        
        /// <remarks/>
        Procesverbaldeconstatareainfractiunilordeaudienta,
        
        /// <remarks/>
        Cereredeinregistrareaudiosauvideo,
        
        /// <remarks/>
        Raportdeexpertizabalistica,
        
        /// <remarks/>
        Raportdeexpertizadactiloscopica,
        
        /// <remarks/>
        Altraportdeexpertiza,
        
        /// <remarks/>
        Alterapoartedeconstatari,
        
        /// <remarks/>
        Memoriuderecursininteresullegii,
        
        /// <remarks/>
        intampinare,
        
        /// <remarks/>
        Adresasolicitaretaxadetimbrutimbrujudiciarsicopiihotararijudecatoresti,
        
        /// <remarks/>
        Adresasolicitarecopiihotararijudecatoresti,
        
        /// <remarks/>
        Adresasolicitaretaxadetimbrusitimbrujudiciar,
        
        /// <remarks/>
        Adresasolicitaretaxadetimbru,
        
        /// <remarks/>
        Adresasolicitaretimbrujudiciar,
        
        /// <remarks/>
        Adresasolicitaredosar,
        
        /// <remarks/>
        Adresarestituiredosar,
        
        /// <remarks/>
        Adresaprecizareobiectmemoriu,
        
        /// <remarks/>
        Comunicaresolutietermenderecursinanulareexpirat,
        
        /// <remarks/>
        Comunicaresolutieanularememoriucanetimbrat,
        
        /// <remarks/>
        Comunicaresolutienusuntmotivederecursinanulare,
        
        /// <remarks/>
        Comunicaresolutiecauzaseaflaincursdejudecata,
        
        /// <remarks/>
        Comunicaresolutietransmiterememoriuorganuluicompetent,
        
        /// <remarks/>
        AdresacatreCSJdeinaintarerecursinanulare,
        
        /// <remarks/>
        Adresadeinstiintareainstanteidefondcasadeclaratrecursinanulare,
        
        /// <remarks/>
        Adresadeinstiintarepetentcasadeclaratrecursinanulare,
        
        /// <remarks/>
        Propunerepentrupromovarearecursuluiinanulare,
        
        /// <remarks/>
        Propunerepentrupromovarearecursuluiininteresullegii,
        
        /// <remarks/>
        Cereredecomunicaredeinformatii,
        
        /// <remarks/>
        Cereredeobtineredeacte,
        
        /// <remarks/>
        Referat,
        
        /// <remarks/>
        Nota,
        
        /// <remarks/>
        Citatie,
        
        /// <remarks/>
        Altecereri2,
        
        /// <remarks/>
        Alteproceseverbale,
        
        /// <remarks/>
        Alteadrese,
        
        /// <remarks/>
        Rezolutiedeconexare,
        
        /// <remarks/>
        Comunicareasolutieicereriisauplangerii,
        
        /// <remarks/>
        Puneresubinterdictie,
        
        /// <remarks/>
        Declarareabandonminor,
        
        /// <remarks/>
        Apeluri,
        
        /// <remarks/>
        recursuri,
        
        /// <remarks/>
        contestatiideclaratedeprocurorsirespinse,
        
        /// <remarks/>
        Apelurirecursuricontestatiideclaratedepartipemotivedenelegalitate,
        
        /// <remarks/>
        Actiuniintemeiatepeprevederileart504CPP,
        
        /// <remarks/>
        Actiuniindreptateimpotrivaparchetului,
        
        /// <remarks/>
        Practicajudiciaraneunitara,
        
        /// <remarks/>
        Punereinexecutareatitlurilorcivile,
        
        /// <remarks/>
        Rezolutiaprocurorului,
        
        /// <remarks/>
        Ordonantadearestare,
        
        /// <remarks/>
        Ordonantadeconexare,
        
        /// <remarks/>
        Ordonantadedisjungere,
        
        /// <remarks/>
        Ordonantadescoateredesuburmarirepenala,
        
        /// <remarks/>
        Ordonantadeincetareaurmaririipenale,
        
        /// <remarks/>
        Ordonantadeclasare,
        
        /// <remarks/>
        Ordonantadeinfirmaresisauredeschidere,
        
        /// <remarks/>
        Ordonantaderestituireadosaruluilaorganuldecercetarepenala,
        
        /// <remarks/>
        Ordonantadepunereinmiscareaactiuniipenale,
        
        /// <remarks/>
        Ordonantadedeclinare,
        
        /// <remarks/>
        Rezolutiedeincepereaurmaririipenale,
        
        /// <remarks/>
        Rezolutiedescoateredesuburmarirepenala,
        
        /// <remarks/>
        Rezolutiedeincetareaurmaririipenale,
        
        /// <remarks/>
        Rezolutiedeclasare,
        
        /// <remarks/>
        Rezolutiedeinfirmaresisauredeschidere,
        
        /// <remarks/>
        Rezolutiededeclinare,
        
        /// <remarks/>
        Rezolutiederestituireadosaruluilaorganuldecercetarepenala,
        
        /// <remarks/>
        Rezolutiedetrecereacauzeidelaunorganlaaltul,
        
        /// <remarks/>
        Rezolutiedeneincepereaurmaririipenale,
        
        /// <remarks/>
        AvizalMinistruluiJustitieipentrumagistratiexecutorijudecatorestisinotaridetrimitereinjudecata,
        
        /// <remarks/>
        Cerereinlocuiremasuraarestariipreventiveart139CPP,
        
        /// <remarks/>
        Procesverbaldeaducerelacunostintaainvinuiriisiadreptuluilaaparare,
        
        /// <remarks/>
        Anchetasociala,
        
        /// <remarks/>
        Procesverbalderecunoasteredingrup,
        
        /// <remarks/>
        Plansafotografica,
        
        /// <remarks/>
        ReferatdeterminareaurmaririipenaleintocmitdeorganeledePolitie,
        
        /// <remarks/>
        Cereredeincetareamunciicorectionale,
        
        /// <remarks/>
        Cererepentruinlocuireapedepseiamenziicuinchisoarea,
        
        /// <remarks/>
        Cererepentruinlocuireapedepseidetentiuniipeviatacupedeapsainchisorii,
        
        /// <remarks/>
        Declaratiedeabtinere,
        
        /// <remarks/>
        Ordonantadeadmiteriicereriideliberareprovizoriesubcontroljudiciar,
        
        /// <remarks/>
        Ordonantaderespingereacereriideliberareprovizoriesubcontroljudiciar,
        
        /// <remarks/>
        Ordonantadeadmitereacereriideliberareprovizoriepecautiune,
        
        /// <remarks/>
        Ordonantaderespingereacereriideliberareprovizoriepecautiune,
        
        /// <remarks/>
        Ordonantadeluareamasurilorasiguratorii,
        
        /// <remarks/>
        Ordonantadeinterzicerealuariidecontactaaparatoruluicuinculpatul,
        
        /// <remarks/>
        Ordonantadeaplicareauneiamenzijudiciare,
        
        /// <remarks/>
        Ordonantadescoateredesuburmarirepenalasiaplicareauneisanctiunicucaracteradministrativ,
        
        /// <remarks/>
        Ordonantadesuspendareaurmaririipenale,
        
        /// <remarks/>
        Ordonantadeadmitereacererilornoiformulatedeinculpat,
        
        /// <remarks/>
        Ordonantaderespingereacererilornoiformulatedeinculpat,
        
        /// <remarks/>
        Ordonantadetrimitereacauzeilaunaltorgandeurmarireinvedereacompletariisaurefaceriiacesteia,
        
        /// <remarks/>
        Ordonantadereluareaurmaririipenale,
        
        /// <remarks/>
        Rezolutiedeefectuareauneiconstataritehnicostiintifice,
        
        /// <remarks/>
        Rezolutiedeefectuareaunoracteproceduraleprincomisierogatorie,
        
        /// <remarks/>
        Rezolutiededelegare,
        
        /// <remarks/>
        Rezolutiedeluareamasurilordesiguranta,
        
        /// <remarks/>
        Rezolutiederestituirealucrurilor,
        
        /// <remarks/>
        Rezolutiedeindreptareaerorilormateriale,
        
        /// <remarks/>
        Rezolutiedeinlaturareaunoromisiunivadite,
        
        /// <remarks/>
        Rezolutiedeextindereacercetariipenale,
        
        /// <remarks/>
        Rezolutiedeinlocuireamasurilorpreventive,
        
        /// <remarks/>
        Rezolutiederevocareamasurilorpreventive,
        
        /// <remarks/>
        Rezolutiedeadmitereaplangeriiimpotrivamasurilorsiactelordeurmarirepenala,
        
        /// <remarks/>
        Rezolutiederespingereaplangeriiimpotrivamasurilorsiactelordeurmarirepenala,
        
        /// <remarks/>
        Cereredereexaminare,
        
        /// <remarks/>
        Notatelefonica2,
        
        /// <remarks/>
        Rezolutiedeinchidere,
        
        /// <remarks/>
        Referatdeinchidere,
        
        /// <remarks/>
        Referatdereexaminare,
        
        /// <remarks/>
        Cereredecomunicareasolutieicereriisauplangerii,
        
        /// <remarks/>
        Cereredeanulareareabilitarii,
        
        /// <remarks/>
        Cererederevocareaarestarii,
        
        /// <remarks/>
        Cererepentruconstatareaincetariidedreptaarestarii,
        
        /// <remarks/>
        Cereredecontestareamasurilorasiguratorii,
        
        /// <remarks/>
        Cerereinprobatoriu,
        
        /// <remarks/>
        Fotografii,
        
        /// <remarks/>
        Cereripentrumajorareaonorariilorexpertilorsiinterpretilor,
        
        /// <remarks/>
        Cereripentrucheltuielidejudecatadinparteamartorilor,
        
        /// <remarks/>
        Obiectivedeexpertizacerutedepartisaudeprocuror,
        
        /// <remarks/>
        Memoriudepromovarerevizuiredecatreprocuror,
        
        /// <remarks/>
        Memoriudepromovarecontestatieinanularedecatreprocuror,
        
        /// <remarks/>
        Actenotariale,
        
        /// <remarks/>
        Altedocumente,
        
        /// <remarks/>
        Adresasupraveghere,
        
        /// <remarks/>
        Adresadeinaintaretrimiteredosar,
        
        /// <remarks/>
        Cererestudiudosar,
        
        /// <remarks/>
        Adresasolicitaredatesauinformatii,
        
        /// <remarks/>
        Adresasolicitareacte,
        
        /// <remarks/>
        Comunicaresolutiedosar,
        
        /// <remarks/>
        Comunicareptrplataamenziiadministrativesicheltuielijudiciare,
        
        /// <remarks/>
        Referatpunereinmiscareaactiuniipensiarestarepreventiva,
        
        /// <remarks/>
        Cereredeinscriereinfals,
        
        /// <remarks/>
        Cereredecompletareauneiomisiuni,
        
        /// <remarks/>
        Cererederevizuireahotararii,
        
        /// <remarks/>
        Cereredeindreptareahotararii,
        
        /// <remarks/>
        Cereredecompletareahotararii,
        
        /// <remarks/>
        Cerereptlamurireaintelesuluiintinderiisauaplicariidispozitivuluihotararii,
        
        /// <remarks/>
        Cereredepreschimbareatermenuluidejudecata,
        
        /// <remarks/>
        Cereredestabilireacautiunii,
        
        /// <remarks/>
        Cereredeanulareaunuititluhotarariarbitraleetc,
        
        /// <remarks/>
        Cereredesuspendareahotararii,
        
        /// <remarks/>
        Cereredepoprireasiguratorie,
        
        /// <remarks/>
        Actiuneinconstatareanulitatiiabsoluteaunuiactjuridic,
        
        /// <remarks/>
        Actiuneinanulare,
        
        /// <remarks/>
        Cereredestabilireacompetentei,
        
        /// <remarks/>
        Cererepentrulipsadeaparare,
        
        /// <remarks/>
        Cereredeamanareaplatiitaxeidetimbru,
        
        /// <remarks/>
        Cereredescutireaplatiitaxeidetimbru,
        
        /// <remarks/>
        Cereredesuspendareajudecatii,
        
        /// <remarks/>
        Cereredecitarelaaltaadresa,
        
        /// <remarks/>
        Cereredecitareprinafisare,
        
        /// <remarks/>
        Dovadadeindeplinireaproceduriidecitare,
        
        /// <remarks/>
        Notescrise,
        
        /// <remarks/>
        Dovadadeachitaretaxadetimbru,
        
        /// <remarks/>
        Contestatieinmoduldestabilireataxeidetimbru,
        
        /// <remarks/>
        Cereredeintroducereaaltorparti,
        
        /// <remarks/>
        Motivederecurs,
        
        /// <remarks/>
        Actenoipentrucomunicarearecurentului,
        
        /// <remarks/>
        Actenoipentrucomunicareaintimatului,
        
        /// <remarks/>
        Anuntareaschimbariisediuluisaudenumirii,
        
        /// <remarks/>
        Comunicare,
        
        /// <remarks/>
        Ordonanta,
        
        /// <remarks/>
        Cereredecomunicaresolutiedosar,
        
        /// <remarks/>
        Cereredecomunicarestadiucercetari,
        
        /// <remarks/>
        Cerereavizcercetare,
        
        /// <remarks/>
        Cerereaviztrimitereinjudecata,
        
        /// <remarks/>
        Fisacriminologica,
        
        /// <remarks/>
        OrdinalMinistruluiJustitieipentruextradare,
        
        /// <remarks/>
        Ordonantaderevocareamasuriiarestariipreventive,
        
        /// <remarks/>
        Comunicaremotivedeapel,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindadoptiaunorminori,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddesfacereaunoradoptii,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindpunereasubinterdictie,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindincheiereadesentintecivile,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinregistrareapartidelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinregistrareaaliantelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindmodificareastatutuluipartidelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindmodificareastatutuluialiantelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindfuziuneapartidelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindfuziuneaaliantelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddizolvareapartidelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddizolvareaaliantelorpolitice,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinfiintareasindicatelor,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinfiintareauniunilorfederatiilorsauconfederatiilordesindicat,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindmodificareastatutuluisindicateloruniunilorfederatiilorsauconfederatiilordesindicat,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinregistrari,
        
        /// <remarks/>
        modificarisaudizolvarideasociatiisifundatii,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddecaderidindrepturiparintesti,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddeclarareadisparitiilor,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivinddeclarareamortiiprezumate,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindinregistrareasirectificareaunoractecivile,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindnulitateaadoptiei,
        
        /// <remarks/>
        ComunicareahotararilorcivileprivindanulareaunoracteadministrativeconfOG132001,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindactiunilededespagubireconfart504CPP,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindactiunilestatuluideexproprierepentrucauzedeutilitate,
        
        /// <remarks/>
        Comunicarecitatii,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindcerereadedeclararejudecatoreascaaabandonului,
        
        /// <remarks/>
        incheieredesedinta2,
        
        /// <remarks/>
        Decizie,
        
        /// <remarks/>
        Minuta,
        
        /// <remarks/>
        Referatpropunerepromovarerecursinanularedosar,
        
        /// <remarks/>
        incheieredestramutare,
        
        /// <remarks/>
        incheieredeamanare,
        
        /// <remarks/>
        Recursinanularepromovatlacerereapartilor,
        
        /// <remarks/>
        Recursininteresullegii,
        
        /// <remarks/>
        DelegatiiindosareleincareMinisterulPublicesteparte,
        
        /// <remarks/>
        Conflictedecompetenta,
        
        /// <remarks/>
        Informariprivindcauzeimportanteaflateperolulinstantelor,
        
        /// <remarks/>
        FisagardaFinanciara,
        
        /// <remarks/>
        ComunicareahotararilorcivileprivindLegeanr5502002,
        
        /// <remarks/>
        ComunicareahotararilorcivileprivindOUG1902000,
        
        /// <remarks/>
        Referatcupropuneredeterminareaurmaririipenale,
        
        /// <remarks/>
        Referatcupropuneredescoateredesuburmarirepenala,
        
        /// <remarks/>
        Referatcupropuneredescoateredesuburmarirepenalacuaplicareauneiamenzicucaracteradministrativ181Cp,
        
        /// <remarks/>
        Referatcupropuneredeincetareaurmaririipenale,
        
        /// <remarks/>
        Referatcupropuneredeclasareacauzei,
        
        /// <remarks/>
        Referatcupropuneredeneincepereaurmaririipenale,
        
        /// <remarks/>
        Referatcupropuneredeconexare,
        
        /// <remarks/>
        Referatcupropunerededeclinareacompetentei,
        
        /// <remarks/>
        Adresasesizarecomandant,
        
        /// <remarks/>
        Motivederecurs2,
        
        /// <remarks/>
        Cereredeamanare,
        
        /// <remarks/>
        Cerereamanare,
        
        /// <remarks/>
        acordaretermenpentrulipsadeaparare,
        
        /// <remarks/>
        Precizari,
        
        /// <remarks/>
        CopieminutadeciziedelaCSJ,
        
        /// <remarks/>
        Motivedeapel,
        
        /// <remarks/>
        Cerereinurgentareredactarehotarare,
        
        /// <remarks/>
        Confirmaretitluexecutoriu,
        
        /// <remarks/>
        Confirmaredebit,
        
        /// <remarks/>
        Mandatdetransfer,
        
        /// <remarks/>
        Cererederetragereaapeluluirecursului,
        
        /// <remarks/>
        Extrascertificatdedeces,
        
        /// <remarks/>
        DeclaratierecursainculpatuluipartiivatamatepartiicivilepartiiresponsabilecivilmenteParchetului,
        
        /// <remarks/>
        Declaratierecursainculpatului,
        
        /// <remarks/>
        Copiaminuteidecizieipenale,
        
        /// <remarks/>
        Dovadadeindeplinireaproceduriidecomunicare,
        
        /// <remarks/>
        Adresapentrudareindebitlaadministartiafinantelorpublice,
        
        /// <remarks/>
        Adresaderaspunsaadministartieifinantelorpublicepepreluareadebitului,
        
        /// <remarks/>
        Cererecomunicarehotararealteacte,
        
        /// <remarks/>
        Cererederenuntarelajudecata,
        
        /// <remarks/>
        Adresacomunicarerelatii,
        
        /// <remarks/>
        Cererejudecareinlipsa,
        
        /// <remarks/>
        Anexa,
        
        /// <remarks/>
        Copieminutaincheiere,
        
        /// <remarks/>
        Procesverbal,
        
        /// <remarks/>
        Comunicaredeciziepenalaincheiere,
        
        /// <remarks/>
        Cereredeamanarelaadouastrigare,
        
        /// <remarks/>
        Cereredeincuviintareaexecutariisilite,
        
        /// <remarks/>
        OficiulRegistruluiComertuluidepelangaTribunalulCluj,
        
        /// <remarks/>
        Referatcupropuneripromovarerecursininteresullegii,
        
        /// <remarks/>
        Referatcupropuneripromovarerecursinanulare,
        
        /// <remarks/>
        OrdinalProcuroruluiGeneral,
        
        /// <remarks/>
        Motivedeapel2,
        
        /// <remarks/>
        Motivederecurs3,
        
        /// <remarks/>
        Referatdeachitare,
        
        /// <remarks/>
        Referatderestituire,
        
        /// <remarks/>
        Raport,
        
        /// <remarks/>
        Adresa,
        
        /// <remarks/>
        Alteevidente,
        
        /// <remarks/>
        Documentatie,
        
        /// <remarks/>
        Inventar,
        
        /// <remarks/>
        Adeverinta,
        
        /// <remarks/>
        Analiza,
        
        /// <remarks/>
        Tematica,
        
        /// <remarks/>
        Situatie,
        
        /// <remarks/>
        Delegatie,
        
        /// <remarks/>
        Referatdearestarecunetrimitereinjudecata,
        
        /// <remarks/>
        Cereredeaudienta,
        
        /// <remarks/>
        Delegatie2,
        
        /// <remarks/>
        Recursinanulare,
        
        /// <remarks/>
        Procesverbaldeindeplinireaproceduriideinmanareaunoracte,
        
        /// <remarks/>
        Planificare,
        
        /// <remarks/>
        Procesverbaldeconstataredepistare,
        
        /// <remarks/>
        Cereredeinregistraretardivaadecesului,
        
        /// <remarks/>
        Dovadadeinregistraretardivaadecesului,
        
        /// <remarks/>
        Regulatordecompetenta,
        
        /// <remarks/>
        DecizieainalteiCurtideCasatiesiJustitie,
        
        /// <remarks/>
        Notadestudiu,
        
        /// <remarks/>
        Cereredeincadrare,
        
        /// <remarks/>
        Cererederecalcularedrepturibanesti,
        
        /// <remarks/>
        Cereredeconcediu,
        
        /// <remarks/>
        Cereredeconcediupentrucresterecopil,
        
        /// <remarks/>
        Cerereeliberarelegitimatiedeserviciu,
        
        /// <remarks/>
        Cereredetreceredelaosectielaalta,
        
        /// <remarks/>
        Cereredereluareaactivitatiidupaconcediupentrucresterecopil,
        
        /// <remarks/>
        Cereredetransfer,
        
        /// <remarks/>
        Cereredenumire,
        
        /// <remarks/>
        Cererededecontaremedicamente,
        
        /// <remarks/>
        Cererededecontaretransport,
        
        /// <remarks/>
        Cererededelegare,
        
        /// <remarks/>
        Cererededetasare,
        
        /// <remarks/>
        Cereredepromovare,
        
        /// <remarks/>
        Cereredeeliberareadeverinta,
        
        /// <remarks/>
        Cereredeeliberaredinfunctie,
        
        /// <remarks/>
        Cereredepensionare,
        
        /// <remarks/>
        Informareeveniment,
        
        /// <remarks/>
        Concluziiscrise,
        
        /// <remarks/>
        Cereredelasarelaurmasedintei,
        
        /// <remarks/>
        Cereredesolicitarecertificat,
        
        /// <remarks/>
        Obiectiunilaraportdeexpertiza,
        
        /// <remarks/>
        Cereredenedeclararerecursimpotrivaincheieriidecizieipenale,
        
        /// <remarks/>
        Restituirenotegrefierdesedinta,
        
        /// <remarks/>
        Cereredeneconstituirepartecivila,
        
        /// <remarks/>
        Cereredeconstituirepartecivila,
        
        /// <remarks/>
        Cererereferitoarelacauzaincursdejudecata,
        
        /// <remarks/>
        Cereredeasistentajudiciarainternationala,
        
        /// <remarks/>
        DecizieaCurtiiConstitutionale,
        
        /// <remarks/>
        Cereredeplataoresuplimentare,
        
        /// <remarks/>
        Optiuneinurmaexamenuluidecapacitate,
        
        /// <remarks/>
        Adresadetrimiterememoriuplangere,
        
        /// <remarks/>
        Adresacupropuneredeanusedeclararecurs,
        
        /// <remarks/>
        Ordonantadestabilireacompetentei,
        
        /// <remarks/>
        Rezolutiedeconfirmare,
        
        /// <remarks/>
        Cererepentrusolutionareaconflictuluinegativdecompetenta,
        
        /// <remarks/>
        Comunicareahotararilorcivileprivindsolutionareacererilordeindreptareaeroriimateriale,
        
        /// <remarks/>
        Situatieprivindcauzeleavandobiectdreptuldeproprietateintelectuala,
        
        /// <remarks/>
        Copiaminuteisentinteipenale,
        
        /// <remarks/>
        Cereredeinvestire,
        
        /// <remarks/>
        Mandatdeexecutareapedepseiinchisorii,
        
        /// <remarks/>
        Comunicareextras,
        
        /// <remarks/>
        Comunicaretitlucatredebitor,
        
        /// <remarks/>
        Dovadacomunicariicatredebitor,
        
        /// <remarks/>
        Comunicaretitlucatreorganuldeexecutare,
        
        /// <remarks/>
        Cerere,
        
        /// <remarks/>
        Invitatie,
        
        /// <remarks/>
        Reclamatie,
        
        /// <remarks/>
        Petitie,
        
        /// <remarks/>
        instiintare,
        
        /// <remarks/>
        Documentatiedespecialitate,
        
        /// <remarks/>
        Carte,
        
        /// <remarks/>
        Revista,
        
        /// <remarks/>
        Oferta,
        
        /// <remarks/>
        Felicitare,
        
        /// <remarks/>
        Dovadadepunerecautiune,
        
        /// <remarks/>
        Cerereintroductivapentrudeaschidereaproceduriiinsolventeilacerereacreditorului,
        
        /// <remarks/>
        Certificat2,
        
        /// <remarks/>
        Renuntarelacaleadeatac,
        
        /// <remarks/>
        Cerereadefixareaunuitermendeurgenta,
        
        /// <remarks/>
        Interogatoriu,
        
        /// <remarks/>
        Documenteindosar,
        
        /// <remarks/>
        cereredesesizareaCurtiiConstitutionale,
        
        /// <remarks/>
        propuneredearestarepreventiva,
        
        /// <remarks/>
        cererededobandireapersonalitatiijuridice,
        
        /// <remarks/>
        incheieredeamanareajudecarii,
        
        /// <remarks/>
        incheieredeexecutaresilita,
        
        /// <remarks/>
        incheieresesizareCJUE,
        
        /// <remarks/>
        Opinieseparata,
        
        /// <remarks/>
        Hotarareintermediara,
        
        /// <remarks/>
        Buletinstatisticpentrudivort,
        
        /// <remarks/>
        Fisacriminologicaavictimei,
        
        /// <remarks/>
        Fisainculpatului,
        
        /// <remarks/>
        Rezolutieprimireacereriidechemareinjudecata,
        
        /// <remarks/>
        AdresalaEvidentaPersoaneipentrucomunicaredomiciliuresedinta,
        
        /// <remarks/>
        AdresaRegistrulCometuluipentrucomunicaresediu,
        
        /// <remarks/>
        AdresaBirouNotarialpentrucertificatdemostenitor,
        
        /// <remarks/>
        AdresaCameraNotarilorpentruverificaredeschideresuccesiune,
        
        /// <remarks/>
        AdresEvidentaPersoaneipentrucomunicareCNP,
        
        /// <remarks/>
        Asigurareprezentaminor,
        
        /// <remarks/>
        AdresaDGASPCpentruraportevaluare,
        
        /// <remarks/>
        AdresaAutoritatetutelarapentruanchetasociala,
        
        /// <remarks/>
        Adresapentruveniturinete,
        
        /// <remarks/>
        AdresaAFPpentruvenituricastigurinete,
        
        /// <remarks/>
        AdresaAFPpentrubilantcontabil,
        
        /// <remarks/>
        ProcesverbalascultareminorL2722004,
        
        /// <remarks/>
        ProcesverbalascultareminorCFam,
        
        /// <remarks/>
        Incheieredeinfiintarepoprire,
        
        /// <remarks/>
        Adresapentrucomunicarepoprire,
        
        /// <remarks/>
        Adresapentruactecareaustatlabazaemiteriiautorizatieideconstruire,
        
        /// <remarks/>
        Adresapentruactecareaustatlabazaemiteriititluluideproprietate,
        
        /// <remarks/>
        Adresapentrucomunicaresituatiejuridica,
        
        /// <remarks/>
        Adresapentruistoricadresaimobil,
        
        /// <remarks/>
        Adresapentruistoricrolfiscal,
        
        /// <remarks/>
        Adresapentruactecareaustatlabazaemiteriidispozitiei,
        
        /// <remarks/>
        Adresapentrucopiecontractdeinchiriere,
        
        /// <remarks/>
        AdresapentruinscrisuricareaustatlabazainscrieriiinCFindividuala,
        
        /// <remarks/>
        Adresapentrucomunicaresolutionarelitigiu,
        
        /// <remarks/>
        AdresapentrucopieCFcolectiva,
        
        /// <remarks/>
        Adresapentrunotarelitigiuactjuridicincheiatlanotar,
        
        /// <remarks/>
        Adresapentrunotarelitigiuactjuridictitludeproprietate,
        
        /// <remarks/>
        Adresapentruinscrieresechestru,
        
        /// <remarks/>
        Adresapentruradieresechestru,
        
        /// <remarks/>
        Adresapentrucomunicarehotarareconstatarenulitate,
        
        /// <remarks/>
        Adresaprivindsolutionareacaiideatacimpotrivaincheieriijudecatoruluidelegat,
        
        /// <remarks/>
        AdresaDGFPpentrucomunicaredizolvare,
        
        /// <remarks/>
        Adresaexpertpentruefectuareexpertiza,
        
        /// <remarks/>
        AdresaIMLpentruexpertiza,
        
        /// <remarks/>
        AdresaANPCpentruexpertiza,
        
        /// <remarks/>
        Adresaexpertpentrusuplimentexpertiza,
        
        /// <remarks/>
        Adresaexpertpentruexpertizanoua,
        
        /// <remarks/>
        Adresaexpertpentruraspunslaobiectiuni,
        
        /// <remarks/>
        AdresaBLETpentrucomunicarenumireexpert,
        
        /// <remarks/>
        AdresacatreCameradevaloriainstantei,
        
        /// <remarks/>
        AdresacatreINS,
        
        /// <remarks/>
        Adresapentrudovadacomunicareprocesverbaldecontraventie,
        
        /// <remarks/>
        Adresapentrudateinmatriculareautovehicol,
        
        /// <remarks/>
        Adresadeclinare,
        
        /// <remarks/>
        Adresatrimiteredosarincaleadeatac,
        
        /// <remarks/>
        Adresarestituiredosardincaleadeatac,
        
        /// <remarks/>
        Adresarestituiredosardupaefectuareacomisieirogatorii,
        
        /// <remarks/>
        AdresaAFPpentrucomunicaretitluexecutoriuamendajudiciara,
        
        /// <remarks/>
        AdresaAFPpentrucomunicareadmiterecereredereexaminare,
        
        /// <remarks/>
        Mandatuldearestarepreventiva,
        
        /// <remarks/>
        Procesverbaldeincunostintaredespreluareamasuriiarestariipreventive,
        
        /// <remarks/>
        Procesverbalcareconsemneazadeclarareanedeclararearecursuluiinsedintapublica,
        
        /// <remarks/>
        Adresaincazulprelungiriiarestariipreventive,
        
        /// <remarks/>
        Adresaincazulinlocuiriimasuriiarestariipreventivecumasuraobligariideanuparasitaracomunicarelapolitie,
        
        /// <remarks/>
        Adresainlocuireaarestariipreventivecuobligatiadeanuparasitaracomunicarelapolitiadefrontiera,
        
        /// <remarks/>
        AdresainlocuireaarestariipreventivecumasuraobligariideanuparasitaracomunicarelaServiciulPasapoarte,
        
        /// <remarks/>
        Adresaincazulincetariidedreptamasuriiarestariipreventive,
        
        /// <remarks/>
        AdresaincazulprelungiriimasuriiobligariideanuparasilocalitateataracomunicarelaPolitie,
        
        /// <remarks/>
        AdresaincazulprelungiriimasuriiobligariideanuparasitaracomunicarePolitiadefrontiera,
        
        /// <remarks/>
        AdresaincazulprelungiriimasuriiobligariideanuparasitaracomunicareServiciulpasapoarte,
        
        /// <remarks/>
        Autorizatiadeperchezitiecontinut,
        
        /// <remarks/>
        Adresapentruaflareadomiciliului,
        
        /// <remarks/>
        Adresapentruaflareasediuluiuneisocietaticomerciale,
        
        /// <remarks/>
        AdresalANPpentrutransferareaunuidetinutaflatintrunaltpenitenciar,
        
        /// <remarks/>
        Dispozitiepentrutransferareaunuidetinutaflatintrunaltpenitenciar,
        
        /// <remarks/>
        AdresaANPpentruaverificadacauninculpatestearestatintrunpenitenciar,
        
        /// <remarks/>
        Adresapentruaverificainregistrareadecesuluiuneiparti,
        
        /// <remarks/>
        Adresapentruaverificainregistrareadeschideriisuccesiuniiuneiparti,
        
        /// <remarks/>
        Adresapentruaflareamosenitoriloruneiparti,
        
        /// <remarks/>
        Mandatuldearestarepreventivamasuraluataincursuljudecatii,
        
        /// <remarks/>
        Mandatuldearestarepreventivamasuraluataprinhotarareadecondamnare,
        
        /// <remarks/>
        Adresaincazulmentineriiarestariipreventiveincursuljudecatii,
        
        /// <remarks/>
        Adresaincazulrevocariiarestariipreventiveincursuljudecatii,
        
        /// <remarks/>
        Adresaincazulmentineriiarestariipreventivelaprimireadosarului,
        
        /// <remarks/>
        Adresaincazulrevocariiarestariipreventivelaprimireadosarului,
        
        /// <remarks/>
        Adresainlocuireaarestariipreventivecuobligatiadeanuparasilocalitateataracomunicarelaloculdedetinere,
        
        /// <remarks/>
        Adresaincazulrevocariimasuriiarestariipreventive,
        
        /// <remarks/>
        Adresaincazulluariimasuriiobligariideanuparasilocalitateataracomunicarelapolitie,
        
        /// <remarks/>
        Adresaincazulluariimasuriiobligariideanuparasitaracomunicarelapolitiadefrontiera,
        
        /// <remarks/>
        AdresaincazulluariimasuriiobligariideanuparasitaracomunicareServiciulPasapoarte,
        
        /// <remarks/>
        Desemnareaunuiavocatdinoficiue,
        
        /// <remarks/>
        Efectuareauneiexpertizedecatreoinstitutie,
        
        /// <remarks/>
        Efectuareauneiexpertizedecatreunexpertdesemnatdeinstanta,
        
        /// <remarks/>
        Obtinereafiseidecazierjudiciar,
        
        /// <remarks/>
        Solicitareauneihotararipronuntatadeoaltainstanta,
        
        /// <remarks/>
        Solicitareaunuidosaralalteiinstanteunuiparchet,
        
        /// <remarks/>
        Restituireaunuidosaral_alteiinstanteunuiparchet,
        
        /// <remarks/>
        Inaintareadosaruluiinvedereasolutionariicereriiderecuzareaintregiiinstante,
        
        /// <remarks/>
        EfectuareaunuireferatdeevaluaredecatreServiciuldeprotectieavictimelorsireintegraresocialaainfractorilor,
        
        /// <remarks/>
        Inaintareaunuidosarlasolicitareaalteiinstanteunuiparchet,
        
        /// <remarks/>
        Inaintareaunuidosarinstanteideapelinvedereasolutionariicaiideatac,
        
        /// <remarks/>
        Inaintareaunuidosarinstanteiderecursinvedereasolutionariicaiideatac,
        
        /// <remarks/>
        Restituireaunuidosardecatreinstantadecontroljudiciardupasolutionareacaiideatac,
        
        /// <remarks/>
        AdresadeinaintareamandatuluilaPolitieinvedereapuneriiinexecutare,
        
        /// <remarks/>
        Mandatuldeexecutareapedepseiinchisoriirevenire,
        
        /// <remarks/>
        InterzicereaunordrepturicomunicareCentrumilitar,
        
        /// <remarks/>
        Masuridesigurantacucaractermedicalinternare,
        
        /// <remarks/>
        Masuridesigurantacucaractermedicalobligarelatratament,
        
        /// <remarks/>
        Adresapentruevidentaamanarilorsisauintreruperilorexecutariipedepsei,
        
        /// <remarks/>
        Comunicaricatreinstantadeexecutaresentintapenala,
        
        /// <remarks/>
        Comunicaricatreinstantadeexecutareextrasdeciziepenala,
        
        /// <remarks/>
        ComunicareaextrasuluidepetitlulexecutoriuCheltuielijudiciare,
        
        /// <remarks/>
        PunereainexecutareacheltuielilorjudiciareamenzilorconfiscariispecialeAdresapentruaflareaCNPdebitori,
        
        /// <remarks/>
        PunereainexecutareamasuriieducativeainternariiincentrudereeducarecomunicarePolitie,
        
        /// <remarks/>
        adresaANPcomunicaretermen,
        
        /// <remarks/>
        adresaANPtrimiterecitatie,
        
        /// <remarks/>
        adresaConsiliullocalcomunicaretermen,
        
        /// <remarks/>
        Adresaexpedierecopiedecizie,
        
        /// <remarks/>
        adresainterpret,
        
        /// <remarks/>
        adresamotiverecurs,
        
        /// <remarks/>
        AdresaPenitenciarcomunicaretermen,
        
        /// <remarks/>
        adresapenitenciarexpedierecopiedecizie,
        
        /// <remarks/>
        AdresaPolitietrimiterecitatie,
        
        /// <remarks/>
        adresarevenireSP,
        
        /// <remarks/>
        adresastramutare,
        
        /// <remarks/>
        adresatrimiteredosar,
        
        /// <remarks/>
        Baroucerereaparatorioficiu,
        
        /// <remarks/>
        Baroucomunicareonorariu,
        
        /// <remarks/>
        Baroucomunicaretermen,
        
        /// <remarks/>
        formulardeciziecsj,
        
        /// <remarks/>
        formularminutacsj,
        
        /// <remarks/>
        Formularverifarestareprevent,
        
        /// <remarks/>
        instiintaremotiverecurs,
        
        /// <remarks/>
        SEadresacomunicaretermenjudecata,
        
        /// <remarks/>
        AdresatrimiteredosarSCA,
        
        /// <remarks/>
        Formularmandateuropeandearestare,
        
        /// <remarks/>
        Formularmandatinterceptare,
        
        /// <remarks/>
        Formularmandatperchezitie,
        
        /// <remarks/>
        Formularmandaturmarireeuropeana,
        
        /// <remarks/>
        Formularmandaturmarireinternationala,
        
        /// <remarks/>
        HOTaRaRE,
        
        /// <remarks/>
        incheiereRecurs,
        
        /// <remarks/>
        incheierePerchezitie2,
        
        /// <remarks/>
        Mandatarestareincursuljudecatii,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CautareDosareCompletedEventHandler(object sender, CautareDosareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CautareDosareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CautareDosareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dosar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dosar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CautareSedinteCompletedEventHandler(object sender, CautareSedinteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CautareSedinteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CautareSedinteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sedinta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sedinta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591